### ISSUE TITLE
Transmute Verifier fails to verify `did:v1` Credentials Issued by Factom or Mavennet

### ISSUE THREAD

**Issue by srmalley-sphereon** [w3c-ccg/vc-examples#73]
**Factom Issued Credential**
POST https://vc.transmute.world/v0.1.0/verify/credentials
```
{
    "verifiableCredential": {
        "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://www.w3.org/2018/credentials/examples/v1"
        ],
        "id": "http://example.gov/credentials/3732",
        "type": [
            "VerifiableCredential",
            "UniversityDegreeCredential"
        ],
        "issuanceDate": "2020-03-10T04:24:12.164Z",
        "credentialSubject": {
            "id": "did:key:z6Mkg9AkjefxdJFSphkStzXwHQnbweN43mCqA37aANGRxF1o",
            "degree": {
                "type": "BachelorDegree",
                "name": "Bachelor of Science and Arts"
            }
        },
        "issuer": "did:v1:test:nym:z6MkvSbsrm44VnhngbyW2rZk2u9bvSPUSmJwqYjMd4RSJT7A",
        "proof": {
            "type": "Ed25519Signature2018",
            "created": "2020-04-29T13:04:57Z",
            "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..FUGNtv74xIug4YUOGB9lZk0Xw1v49helfIKLwJpbj0FQCHMqCg5H7Urg4iY5hFYXw0EwsfnIsRD20fvah8fLCA",
            "proofPurpose": "assertionMethod",
            "verificationMethod": "did:v1:test:nym:z6MkvSbsrm44VnhngbyW2rZk2u9bvSPUSmJwqYjMd4RSJT7A#z6MkjFhRvbXfjmQ8iFHeYh42cNS7v4CtguLzvwZSXcHe8zqy"
        }
    }
}
```
Yields 400, "{message: {}}"

**Mavennet Issued Credential**
POST https://vc.transmute.world/v0.1.0/verify/credentials
```
{
    "verifiableCredential": {
        "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://www.w3.org/2018/credentials/examples/v1"
        ],
        "id": "http://example.gov/credentials/3732",
        "type": [
            "VerifiableCredential",
            "UniversityDegreeCredential"
        ],
        "issuanceDate": "2020-03-10T04:24:12.164Z",
        "credentialSubject": {
            "id": "did:key:z6Mkg9AkjefxdJFSphkStzXwHQnbweN43mCqA37aANGRxF1o",
            "degree": {
                "type": "BachelorDegree",
                "name": "Bachelor of Science and Arts"
            }
        },
        "issuer": "did:v1:test:nym:z6MkfG5HTrBXzsAP8AbayNpG3ZaoyM4PCqNPrdWQRSpHDV6J",
        "proof": {
            "type": "Ed25519Signature2018",
            "created": "2020-04-29T12:46:27Z",
            "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..C5L6wDYVhxFfn8EF8Csw4woQwN_92zkzX03JomSlLvtwg1EsJc542SNL_fNMtmrgHNMYXtdQ0AWwqv3wBUy3Bw",
            "proofPurpose": "assertionMethod",
            "verificationMethod": "did:v1:test:nym:z6MkfG5HTrBXzsAP8AbayNpG3ZaoyM4PCqNPrdWQRSpHDV6J#z6MkqfvdBsFw4QdGrZrnx7L1EKfY5zh9tT4gumUGsMMEZHY3"
        }
    }
}
```
Yields 400, "{message: {}}"

**Comment by gannan08** [comment]
It is hard to debug the exact issue without an error message. A possibility is that the DID Resolver fails to resolve the Veres One DID. What resolver software do Transmute and Mavennet depend on?

**Comment by nklomp** [comment]
If I don't pass in application/json as content-type the message is a bit more verbose:

`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body should be object"
}`

Trying the example value from the swagger definition gives the same result. The DIDs also resolve using our universal resolver, so seems to be something within the transmute verifier

**Comment by peacekeeper** [comment]
> A possibility is that the DID Resolver fails to resolve the Veres One DID.

Just guessing, but could this be related to @dmitrizagidulin 's updated v1 Universal Resolver driver, see https://github.com/decentralized-identity/universal-resolver/pull/102 ?

**Comment by dlongley** [comment]
@peacekeeper -- Yes, it's a bug on our end, we accidentally set a flag to force local resolution in what was pushed out. We're going to get it fixed right away and then everyone will need to redeploy. Sorry about that!

**Comment by dlongley** [comment]
Ok, this should be fixed now. It turns out the problem was isolated to DB's verifier so there's no need for anyone else to deploy anything.

@peacekeeper Nothing to do on your end. Thanks!

**Comment by dlongley** [comment]
@srmalley-sphereon Please close this once you can confirm it works. Thanks!

**Comment by srmalley-sphereon** [comment]
I still cannot seem to get the above credentials to verify. I have also tried adding `"checks":["proof"]` in the options (as per the spec), but it doesn't seem to change the results (always HTTP 400).

Is there a different url I should be calling than https://vc.transmute.world/v0.1.0/verify/credentials ?

**Comment by OR13** [comment]
taking a look.

**Comment by OR13** [comment]
reproduced, deploying fix.

**Comment by OR13** [comment]
I believe this has now been fixed, I have tested these payloads with:

https://vc.transmute.world/api/docs/static/index.html#/v0.1.0/post_v0_1_0_verify_credentials

and 

https://vc.transmute.world/api/docs/static/index.html#/v0.0.0/post_v0_0_0_verifier_credentials

**Comment by OR13** [comment]
@srmalley-sphereon  can you confirm?

**Comment by srmalley-sphereon** [comment]
Everything seems to be working now. Thanks!
